plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.culturegenerale.android.tablet'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.culturegenerale.android.tablet'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName 'CGANDROID001'

        buildConfigField 'String', 'FIREBASE_API_KEY', '"AIzaSyBHAVR_Td-VozN7MzMyZqJ046h1T_ggRDc"'
        buildConfigField 'String', 'FIREBASE_PROJECT_ID', '"culturegeneralesync"'
        buildConfigField 'String', 'FIREBASE_STORAGE_BUCKET', '"culturegeneralesync.firebasestorage.app"'
        buildConfigField 'String', 'SMART_API_URL', '"https://europe-west1-culturegeneralesync.cloudfunctions.net/cgweb032Search"'
        buildConfigField 'String', 'CG_CHANNEL', '"CGANDROID001"'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
