const {onRequest}=require('firebase-functions/v2/https');
const {getApps,initializeApp}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore}=require('firebase-admin/firestore');
if(!getApps().length)initializeApp();
const REGION='europe-west1';
const STOP=new Set(['de','du','des','la','le','les','un','une','et','ou','a','au','aux','en','dans','sur','sous','par','pour','avec','sans','ce','cet','cette','ces','qui','que','quoi','quel','quelle','quels','quelles','est','sont','etre','son','sa','ses','leur','leurs','il','elle','ils','elles','on','se','ne','pas','plus','the','of','and','to','in','is','are','an']);
function one(v){return String(v??'').trim()}
function norm(v){return one(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function toks(v){return [...new Set(norm(v).split(/\s+/).filter(t=>t.length>=2&&!STOP.has(t)))]}
function jaccard(a,b){const A=new Set(a),B=new Set(b);if(!A.size&&!B.size)return 1;let inter=0;for(const x of A)if(B.has(x))inter++;return inter/(A.size+B.size-inter||1)}
function grams(v){const s=`  ${norm(v)}  `;const out=new Set();for(let i=0;i<s.length-2;i++)out.add(s.slice(i,i+3));return out}
function dice(a,b){const A=grams(a),B=grams(b);if(!A.size&&!B.size)return 1;let inter=0;for(const x of A)if(B.has(x))inter++;return 2*inter/(A.size+B.size||1)}
function score(a,b){if(norm(a)===norm(b))return 100;return Math.round(100*(.45*jaccard(toks(a),toks(b))+.55*dice(a,b)))}
function pairKey(a,b){return a<b?`${a}|${b}`:`${b}|${a}`}
function cors(req,res){res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Headers','Authorization, Content-Type');res.set('Access-Control-Allow-Methods','POST, OPTIONS');if(req.method==='OPTIONS'){res.status(204).send('');return true}return false}
function json(res,status,body){res.status(status).set('content-type','application/json; charset=utf-8').send(JSON.stringify(body))}
async function requireUser(req){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))throw Object.assign(new Error('Authentification Firebase requise.'),{status:401});return getAuth().verifyIdToken(h.slice(7))}
exports.cgweb025Duplicates=onRequest({region:REGION,timeoutSeconds:540,memory:'2GiB'},async(req,res)=>{if(cors(req,res))return;try{if(req.method!=='POST')return json(res,405,{ok:false,error:'POST attendu.'});const user=await requireUser(req);const threshold=Math.min(Math.max(Number(req.body?.threshold)||82,65),100);const maxPairs=Math.min(Math.max(Number(req.body?.maxPairs)||300,20),800);const snap=await getFirestore().collection('users').doc(user.uid).collection('questions').get();const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>one(r.question));const exact=new Map(),blocks=new Map();for(const r of rows){const n=norm(r.question);if(!exact.has(n))exact.set(n,[]);exact.get(n).push(r.id);const ts=toks(r.question).slice(0,7);const keys=[];for(let i=0;i<ts.length;i++)for(let j=i+1;j<ts.length&&j<i+4;j++)keys.push([ts[i],ts[j]].sort().join('|'));for(const k of keys.slice(0,8)){if(!blocks.has(k))blocks.set(k,[]);const arr=blocks.get(k);if(arr.length<100)arr.push(r.id)}}const byId=new Map(rows.map(r=>[r.id,r]));const candidates=new Set();for(const ids of exact.values())if(ids.length>1)for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)candidates.add(pairKey(ids[i],ids[j]));for(const ids of blocks.values()){if(ids.length>80)continue;for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)candidates.add(pairKey(ids[i],ids[j]))}const pairs=[];for(const key of candidates){const [aId,bId]=key.split('|');const a=byId.get(aId),b=byId.get(bId);if(!a||!b)continue;const s=score(a.question,b.question);if(s<threshold)continue;pairs.push({score:s,exact:s===100,a:{id:a.id,question:a.question,detail:a.detail||'',theme:a.theme||'',megatheme:a.megatheme||'',cg_revision:Number(a.cg_revision||0)},b:{id:b.id,question:b.question,detail:b.detail||'',theme:b.theme||'',megatheme:b.megatheme||'',cg_revision:Number(b.cg_revision||0)}})}pairs.sort((x,y)=>y.score-x.score||String(x.a.id).localeCompare(String(y.a.id),undefined,{numeric:true}));return json(res,200,{ok:true,questionCount:rows.length,candidateCount:candidates.size,pairs:pairs.slice(0,maxPairs),truncated:pairs.length>maxPairs,threshold})}catch(error){return json(res,Number(error?.status)||500,{ok:false,error:error?.message||String(error)})}});
