const {onRequest}=require('firebase-functions/v2/https');
const {getApps,initializeApp}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
if(!getApps().length)initializeApp();
const REGION='europe-west1',MAX_IDS=500;
const FIELDS=['megatheme','theme','question','detail','proposition_a','proposition_b','proposition_c','proposition_d','correct_index','url_quizypedia','url_internet','image_file','image_thumb_file','image_source_url','image_mime','image_width','image_height','image_bytes','image_sha256','image_schema','image_origin','image_original_name','image_updated_ms','non_trouve','status','is_image'];
const STOP=new Set(['de','du','des','la','le','les','un','une','et','ou','a','au','aux','en','dans','sur','sous','par','pour','avec','sans','ce','cet','cette','ces','qui','que','quoi','quel','quelle','quels','quelles','est','sont','etre','son','sa','ses','leur','leurs','il','elle','ils','elles','on','se','ne','pas','plus','the','of','and','to','in','is','are','an']);
function one(v){return String(v??'').trim()}function normalize(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}function searchTokens(d){return[...new Set(normalize([d.megatheme,d.theme,d.question,d.detail,d.proposition_a,d.proposition_b,d.proposition_c,d.proposition_d].filter(Boolean).join(' ')).split(/\s+/).filter(t=>t.length>=2&&!STOP.has(t)))]}
function cors(req,res){res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Headers','Authorization, Content-Type');res.set('Access-Control-Allow-Methods','POST, OPTIONS');if(req.method==='OPTIONS'){res.status(204).send('');return true}return false}function json(res,status,body){res.status(status).set('content-type','application/json; charset=utf-8').send(JSON.stringify(body))}async function requireUser(req){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))throw Object.assign(new Error('Authentification Firebase requise.'),{status:401});return getAuth().verifyIdToken(h.slice(7))}
function idsOf(raw){return[...new Set((Array.isArray(raw)?raw:[]).map(v=>String(v||'').trim()).filter(Boolean))]}
function patchFor(a,v){if(a==='theme'){v=one(v);if(!v)throw Object.assign(new Error('Le nouveau thème est obligatoire.'),{status:400});return{theme:v}}if(a==='megatheme'){v=one(v);if(!v)throw Object.assign(new Error('Le nouveau mégathème est obligatoire.'),{status:400});return{megatheme:v}}if(a==='status')return{status:String(v??'').trim()};if(a==='status_clear')return{status:''};if(a==='image_search_reactivate')return{non_trouve:0};if(a==='image_mark_missing')return{non_trouve:1};throw Object.assign(new Error('Opération non reconnue.'),{status:400})}
function rev(d){const n=Number(d?.cg_revision||0);return Number.isFinite(n)&&n>=0?Math.trunc(n):0}function snapContent(d){const o={};for(const f of FIELDS)if(d[f]!==undefined)o[f]=d[f];return o}function diff(d,p){const o={};for(const[k,v]of Object.entries(p))if(d[k]!==v)o[k]=v;return o}
async function pool(items,worker,n=6){let c=0;const out=[];async function run(){while(true){const i=c++;if(i>=items.length)return;try{out[i]=await worker(items[i],i)}catch(e){out[i]={status:'error',id:String(items[i]?.id||items[i]),error:e?.message||String(e)}}}}await Promise.all(Array.from({length:Math.min(n,Math.max(items.length,1))},()=>run()));return out}
exports.cgweb021Bulk=onRequest({region:REGION,timeoutSeconds:540,memory:'1GiB'},async(req,res)=>{if(cors(req,res))return;try{if(req.method!=='POST')return json(res,405,{ok:false,error:'POST attendu.'});const user=await requireUser(req),body=req.body||{},mode=one(body.mode),db=getFirestore();
if(mode==='list'){const s=await db.collection('users').doc(user.uid).collection('bulk_audits').orderBy('created_ms','desc').limit(12).get();return json(res,200,{ok:true,audits:s.docs.map(d=>({id:d.id,...d.data()}))})}
if(mode==='undo'){const auditId=one(body.auditId);if(!auditId)return json(res,400,{ok:false,error:'auditId manquant.'});const auditRef=db.collection('users').doc(user.uid).collection('bulk_audits').doc(auditId),auditSnap=await auditRef.get();if(!auditSnap.exists)return json(res,404,{ok:false,error:'Journal bulk introuvable.'});const itemSnap=await auditRef.collection('items').limit(MAX_IDS).get();const results=await pool(itemSnap.docs,async itemDoc=>{const item=itemDoc.data()||{},id=String(item.question_id||itemDoc.id),qRef=db.collection('users').doc(user.uid).collection('questions').doc(id),deltaRef=db.collection('users').doc(user.uid).collection('question_search_delta').doc(id);return db.runTransaction(async tx=>{const itemNow=await tx.get(itemDoc.ref),qSnap=await tx.get(qRef),cur=itemNow.data()||{};if(cur.undone)return{status:'already_undone',id};if(!qSnap.exists)return{status:'missing',id};const cloud=qSnap.data()||{},cloudRev=rev(cloud);if(cloudRev!==Number(cur.after_revision))return{status:'conflict',id,cloudRevision:cloudRev};const before=cur.before||{},restore={};for(const f of FIELDS)restore[f]=Object.prototype.hasOwnProperty.call(before,f)?before[f]:FieldValue.delete();const next=cloudRev+1;tx.update(qRef,{...restore,cg_revision:next,cg_base_revision:cloudRev,cg_updated_at:FieldValue.serverTimestamp(),cg_updated_by:'web',cg_writer_id:'cgweb021',cg_writer_label:'Web · CGWEB021',cg_update_source:'CGWEB021_UNDO'});tx.set(deltaRef,{question_id:id,deleted:false,tokens:searchTokens(before),cgindex_updated_at:FieldValue.serverTimestamp()},{merge:true});tx.update(itemDoc.ref,{undone:true,undo_revision:next,undone_ms:Date.now()});return{status:'undone',id}})},5);const counts={undone:0,conflict:0,missing:0,already_undone:0,error:0};for(const r of results)counts[r.status]=(counts[r.status]||0)+1;await auditRef.set({undo_last_ms:Date.now(),undo_counts:counts,status:counts.conflict||counts.error?'undo_partial':'undone'},{merge:true});return json(res,200,{ok:true,auditId,counts,results:results.slice(0,50)})}
const ids=idsOf(body.ids);if(!ids.length)return json(res,400,{ok:false,error:'Aucun ID sélectionné.'});if(ids.length>MAX_IDS)return json(res,400,{ok:false,error:`Maximum ${MAX_IDS} questions par lot sécurisé.`});const patch=patchFor(one(body.action),body.value);
if(mode==='preview'){const refs=ids.map(id=>db.collection('users').doc(user.uid).collection('questions').doc(id)),snaps=refs.length?await db.getAll(...refs):[],expectedRevisions={},samples=[];let existing=0,changeCount=0,unchanged=0,missing=0;for(let i=0;i<snaps.length;i++){const s=snaps[i],id=ids[i];if(!s.exists){missing++;continue}existing++;const d=s.data()||{},r=rev(d);expectedRevisions[id]=r;const effective=diff(d,patch);if(!Object.keys(effective).length){unchanged++;continue}changeCount++;if(samples.length<30)samples.push({id,revision:r,before:Object.fromEntries(Object.keys(patch).map(k=>[k,d[k]??null])),after:effective})}return json(res,200,{ok:true,mode:'preview',requested:ids.length,patch,existing,changeCount,unchanged,missing,expectedRevisions,samples})}
if(mode!=='apply')return json(res,400,{ok:false,error:'Mode attendu : preview, apply, undo ou list.'});const expected=body.expectedRevisions&&typeof body.expectedRevisions==='object'?body.expectedRevisions:{},auditRef=db.collection('users').doc(user.uid).collection('bulk_audits').doc();await auditRef.set({operation:one(body.action),value:body.value??null,requested_count:ids.length,created_ms:Date.now(),status:'running',source:'CGWEB021'});const results=await pool(ids,async id=>{const qRef=db.collection('users').doc(user.uid).collection('questions').doc(id),deltaRef=db.collection('users').doc(user.uid).collection('question_search_delta').doc(id),itemRef=auditRef.collection('items').doc(id);return db.runTransaction(async tx=>{const s=await tx.get(qRef);if(!s.exists)return{status:'missing',id};const cloud=s.data()||{},cloudRev=rev(cloud),expectedRev=Number(expected[id]);if(!Number.isFinite(expectedRev)||expectedRev!==cloudRev)return{status:'conflict',id,expectedRevision:Number.isFinite(expectedRev)?expectedRev:null,cloudRevision:cloudRev};const effective=diff(cloud,patch);if(!Object.keys(effective).length)return{status:'unchanged',id};const before=snapContent(cloud),after={...cloud,...effective},next=cloudRev+1;tx.set(itemRef,{question_id:id,before,patch:effective,before_revision:cloudRev,after_revision:next,undone:false,created_ms:Date.now()});tx.update(qRef,{...effective,cg_revision:next,cg_base_revision:cloudRev,cg_updated_at:FieldValue.serverTimestamp(),cg_updated_by:'web',cg_writer_id:'cgweb021',cg_writer_label:'Web · CGWEB021',cg_update_source:'CGWEB021_BULK'});tx.set(deltaRef,{question_id:id,deleted:false,tokens:searchTokens(after),cgindex_updated_at:FieldValue.serverTimestamp()},{merge:true});return{status:'updated',id,revision:next}})},6);const counts={updated:0,conflict:0,missing:0,unchanged:0,error:0};for(const r of results)counts[r.status]=(counts[r.status]||0)+1;await auditRef.set({completed_ms:Date.now(),counts,status:counts.conflict||counts.error?'partial':'done'},{merge:true});return json(res,200,{ok:true,auditId:auditRef.id,counts,results:results.filter(r=>r.status!=='updated').slice(0,80)})
}catch(e){return json(res,Number(e?.status)||500,{ok:false,error:e?.message||String(e)})}});
