const {onRequest} = require('firebase-functions/v2/https');
const {initializeApp} = require('firebase-admin/app');
const {getAuth} = require('firebase-admin/auth');
const cheerio = require('cheerio');
initializeApp();

const STOP = new Set(['navigation','communaute','soutenir le projet','nom d utilisateur','mot de passe','se connecter','creer un compte','resultats et classements']);
const NOISE = new Set(['confirmer','annuler','fermer','quitter la partie','continuer a jouer','nouvel utilisateur','duree','sur']);
const HEADER=/^(.+?)\s*[\(\[]\s*(\d+)\s*\/\s*(\d+)\s*[\)\]]\s*$/;
const DEFAULT_LABELS=['Auteur','Auteurs','Titre','Résumé','Nom','Prénom','Pays','Ville','Région','Département','Capitale','Date','Année','Naissance','Décès','Lieu','Nationalité','Profession','Fonction','Domaine','Catégorie','Genre','Type','Période','Créateur','Réalisateur','Scénariste','Dessinateur','Compositeur','Interprète','Acteur','Actrice','Personnage','Série','Album','Épisode','Sport','Club','Équipe','Langue','Surnom','Population','Superficie','Altitude','Monnaie','Devise','Capacité','Origine','Famille','Ordre','Classe','Espèce','Variété','Couleur','Matière','Symbole','Numéro','Formule','Record','Publication','Éditeur','Vainqueur','Finaliste','Score','Résultat','Lieu de naissance'];
function clean(s){return String(s??'').replace(/\u00a0|\u202f|\ufeff/g,' ').replace(/\r/g,'\n').replace(/[ \t]+/g,' ').replace(/\n+/g,'\n').trim();}
function one(s){return clean(s).replace(/\s+/g,' ').trim();}
function norm(s){return one(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function linesFromHtml(html){const $=cheerio.load(html);$('script,style,noscript,svg').remove();return clean($.root().text()).split(/\n+/).map(one).filter(Boolean);}
function dynamicLabels(html){const $=cheerio.load(html);const set=new Set(DEFAULT_LABELS);$('dt,th,label,strong,b,i,em').each((_,el)=>{const t=one($(el).text());if(t.length>=1&&t.length<=55)set.add(t)});return [...set].sort((a,b)=>b.length-a.length);}
function badHeader(name){const k=norm(name);return ['quizypedia','connexion','duels','defi','master quiz','themes','publie le','record en','creer un theme','trouver '].some(x=>k.startsWith(x))||/^\d+ fiches?$/.test(k);}
function prepare(lines){const out=[];for(let i=0;i<lines.length;i++){const line=one(lines[i]);if(HEADER.test(line)){out.push(line);continue}if(i+1<lines.length&&/^[\(\[]\s*\d+\s*\/\s*\d+\s*[\)\]]$/.test(one(lines[i+1]))&&!badHeader(line)){out.push(`${line} ${one(lines[++i])}`);continue}out.push(line)}return out;}
function rawFiches(lines){lines=prepare(lines);const out=[];let cur=null,started=false,totalExpected=null;for(const line0 of lines){const line=one(line0);if(!line)continue;const key=norm(line.replace(/^[# *\.\-:]+|[# *\.\-:]+$/g,''));if(started&&(STOP.has(key)||[...STOP].some(x=>key.startsWith(x+' '))||line.startsWith('Contenus ©')))break;const m=line.match(HEADER);if(m&&!badHeader(m[1])){const total=Number(m[3]);if(totalExpected!==null&&total!==totalExpected)continue;totalExpected=total;if(cur)out.push(cur);cur={name:one(m[1]),position:`(${m[2]} / ${m[3]})`,number:Number(m[2]),total,lines:[],fields:[]};started=true;continue}if(cur&&!NOISE.has(key))cur.lines.push(line)}if(cur)out.push(cur);return out;}
function inferLabels(fiches){const counts=new Map(),original=new Map();const min=fiches.length<=4?2:Math.max(2,Math.ceil(fiches.length*.35));for(const f of fiches){const seen=new Set();for(const line of f.lines){if(line.includes(':')){const left=one(line.split(':',1)[0]);if(left.length<=60){const k=norm(left);seen.add(k);if(!original.has(k))original.set(k,left)}}const tokens=line.split(/\s+/);for(let n=1;n<=Math.min(6,tokens.length-1);n++){const prefix=tokens.slice(0,n).join(' ').replace(/[ :]+$/,'');const value=tokens.slice(n).join(' ');if(!value||prefix.length>65||/[,;]$/.test(prefix)||!(/[A-ZÀ-ÖØ-Þ0-9]/.test(prefix[0])))continue;const k=norm(prefix);seen.add(k);if(!original.has(k))original.set(k,prefix)}}for(const k of seen)counts.set(k,(counts.get(k)||0)+1)}return [...counts].filter(([,c])=>c>=min).map(([k])=>original.get(k)).filter(Boolean);}
function parseFields(lines,labels){const normalized=[...new Set([...DEFAULT_LABELS,...labels])].sort((a,b)=>b.length-a.length);const result=[];let current=null;for(const line0 of lines){const line=one(line0);let found=null,value='';if(line.includes(':')){const [left,...rest]=line.split(':');const lk=norm(left);const l=normalized.find(x=>norm(x)===lk);if(l){found=l;value=one(rest.join(':'))}}if(!found){for(const l of normalized){const re=new RegExp('^'+l.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s+','i');if(re.test(line)){found=l;value=one(line.replace(re,''));break}}}if(found){if(value)result.push({label:found,value});current=found;continue}if(current&&result.length){const last=result[result.length-1];if(last.label===current&&line.length<220)last.value=one(last.value+' '+line)}}const dedup=[];const seen=new Set();for(const f of result){const k=norm(f.label)+'|'+norm(f.value);if(!f.value||seen.has(k))continue;seen.add(k);dedup.push(f)}return dedup;}
function detectedTheme(url,html){try{const u=new URL(url);const p=decodeURIComponent(u.pathname).replace(/^\/+|\/+$/g,'');if(p.toLowerCase().startsWith('quiz/'))return one(p.slice(5));}catch{}const $=cheerio.load(html);return one($('h1').first().text())||one($('title').text()).replace(/\s*[|\-–].*$/,'');}
async function requireUser(req){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))throw Object.assign(new Error('Authentification Firebase requise.'),{status:401});return getAuth().verifyIdToken(h.slice(7));}
exports.cgimport002Quizypedia=onRequest({region:'europe-west1',timeoutSeconds:60,memory:'512MiB'},async(req,res)=>{try{if(req.method!=='POST')return res.status(405).json({ok:false,error:'Méthode non autorisée.'});await requireUser(req);const raw=one(req.body?.url);let u;try{u=new URL(raw)}catch{return res.status(400).json({ok:false,error:'URL invalide.'})}if(!/(^|\.)quizypedia\.fr$/i.test(u.hostname))return res.status(400).json({ok:false,error:'Seules les URL quizypedia.fr sont acceptées.'});if(!u.pathname.toLowerCase().includes('/quiz/'))return res.status(400).json({ok:false,error:'Cette URL ne semble pas être une page /quiz/ Quizypedia.'});const response=await fetch(u.toString(),{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36','accept-language':'fr-FR,fr;q=0.9'}});if(!response.ok)throw new Error(`Quizypedia HTTP ${response.status}`);const html=await response.text();const lines=linesFromHtml(html),labels=dynamicLabels(html),fiches=rawFiches(lines),inferred=inferLabels(fiches),allLabels=[...new Set([...labels,...inferred])];for(const f of fiches)f.fields=parseFields(f.lines,allLabels);return res.json({ok:true,requestedUrl:raw,effectiveUrl:response.url,detectedTheme:detectedTheme(response.url,html),fiches:fiches.map(f=>({name:f.name,position:f.position,number:f.number,total:f.total,fullText:f.lines.join(' | '),fields:f.fields}))});}catch(e){console.error('CGIMPORT002',e);return res.status(e.status||500).json({ok:false,error:e.message||'Erreur serveur CGIMPORT002.'})}});
